#!/bin/bash
# Usage ./build-yunohost [ARCH [DIST [DEB_DIST]]]
# ARCH amd64|i386
# DIST stable|testing
# DEB_DIST jessie|stretch

DATE=$(date +%m%d%y%H%M)
DEBNUM='8.9'



# Build Yunohost iso for amd64 or i386 arch
# Usage: build ARCH
function build
{
    REPO_URL="http://repo.yunohost.org/debian/"
    if [ "$DIST" = "testing" ] ; then
        sed -i "s#$REPO_URL jessie stable#$REPO_URL $DEB_DIST stable testing#" profiles/*.preseed
        sed -i "s#$REPO_URL stretch stable#$REPO_URL $DEB_DIST stable testing#" profiles/*.preseed
    else
        sed -i "s#$REPO_URL jessie stable testing#$REPO_URL $DEB_DIST stable#" profiles/*.preseed
        sed -i "s#$REPO_URL stretch stable testing#$REPO_URL $DEB_DIST stable#" profiles/*.preseed
    fi
    build-simple-cdd --dist $DEB_DIST --conf ./simple-cdd-$1.conf
    $(pwd)/add-firmware-to images/debian-$DEBNUM-$1-CD-1.iso images/yunohost-$DEB_DIST-$DATE-$1-$DIST.iso $DEB_DIST
    rm images/debian-$DEBNUM-$1-CD-1.iso
    rm images/debian-$DEBNUM-$1-CD-1.list.gz
}

# Sign the new iso
# Usage: sign ARCH
function sign 
{
    NAME="images/yunohost-$DEB_DIST-$DATE-$1-$DIST.iso"
    gpg --output $NAME.sig --detach-sig $NAME
    sha256sum $NAME > images/SHA256SUM
}

function build_and_sign
{
    build $1
    sign $1
}

rm -r $(pwd)/tmp
DIST=$2
if [[ "${2:-1}" = 1 ]]; then
    DIST='stable'
fi
DEB_DIST=$3
if  [[ "${3:-1}" = 1 ]]; then
    DEB_DIST='jessie'
fi

if [[ "${1:-1}" = 1 ]]
then
	build_and_sign i386
	build_and_sign amd64
else
    build_and_sign $1
fi
